name: 发布文档到github pages
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 获取源码 🛎️
        uses: actions/checkout@v2.3.1

      - name: 安装依赖和构建 🔧
        run: |
          npm i pnpm -g
          pnpm install
          pnpm run docs:build

      - name: 部署 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vitepress/dist # The folder the action should deploy.
