name: Create Release Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Create Release Tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            更新内容请查看[CHANGELOG](https://github.com/agileago/vue3-oop/blob/master/CHANGELOG.md)。
            Please refer to [CHANGELOG](https://github.com/agileago/vue3-oop/blob/master/CHANGELOG.md) for details.
